import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        <link 
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-inter flex flex-col min-h-screen ">
        <Header />
        <div className="grow">{children}</div>
        <Footer /> 
      </body>
    </html>
  );
}
